// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protos/chenmi.proto

package com.share.proto.chenmi;

public final class Chenmi {
  private Chenmi() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ChenmiInfoRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code com.share.proto.chenmi.ChenmiInfoRequest}
   */
  public static final class ChenmiInfoRequest extends
      com.google.protobuf.GeneratedMessage
      implements ChenmiInfoRequestOrBuilder {
    // Use ChenmiInfoRequest.newBuilder() to construct.
    private ChenmiInfoRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ChenmiInfoRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ChenmiInfoRequest defaultInstance;
    public static ChenmiInfoRequest getDefaultInstance() {
      return defaultInstance;
    }

    public ChenmiInfoRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ChenmiInfoRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.share.proto.chenmi.Chenmi.internal_static_com_share_proto_chenmi_ChenmiInfoRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.share.proto.chenmi.Chenmi.internal_static_com_share_proto_chenmi_ChenmiInfoRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.share.proto.chenmi.Chenmi.ChenmiInfoRequest.class, com.share.proto.chenmi.Chenmi.ChenmiInfoRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<ChenmiInfoRequest> PARSER =
        new com.google.protobuf.AbstractParser<ChenmiInfoRequest>() {
      public ChenmiInfoRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChenmiInfoRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ChenmiInfoRequest> getParserForType() {
      return PARSER;
    }

    private void initFields() {
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.share.proto.chenmi.Chenmi.ChenmiInfoRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.share.proto.chenmi.Chenmi.ChenmiInfoRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.share.proto.chenmi.Chenmi.ChenmiInfoRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.share.proto.chenmi.Chenmi.ChenmiInfoRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.share.proto.chenmi.Chenmi.ChenmiInfoRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.share.proto.chenmi.Chenmi.ChenmiInfoRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.share.proto.chenmi.Chenmi.ChenmiInfoRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.share.proto.chenmi.Chenmi.ChenmiInfoRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.share.proto.chenmi.Chenmi.ChenmiInfoRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.share.proto.chenmi.Chenmi.ChenmiInfoRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.share.proto.chenmi.Chenmi.ChenmiInfoRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.share.proto.chenmi.ChenmiInfoRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.share.proto.chenmi.Chenmi.ChenmiInfoRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.share.proto.chenmi.Chenmi.internal_static_com_share_proto_chenmi_ChenmiInfoRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.share.proto.chenmi.Chenmi.internal_static_com_share_proto_chenmi_ChenmiInfoRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.share.proto.chenmi.Chenmi.ChenmiInfoRequest.class, com.share.proto.chenmi.Chenmi.ChenmiInfoRequest.Builder.class);
      }

      // Construct using com.share.proto.chenmi.Chenmi.ChenmiInfoRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.share.proto.chenmi.Chenmi.internal_static_com_share_proto_chenmi_ChenmiInfoRequest_descriptor;
      }

      public com.share.proto.chenmi.Chenmi.ChenmiInfoRequest getDefaultInstanceForType() {
        return com.share.proto.chenmi.Chenmi.ChenmiInfoRequest.getDefaultInstance();
      }

      public com.share.proto.chenmi.Chenmi.ChenmiInfoRequest build() {
        com.share.proto.chenmi.Chenmi.ChenmiInfoRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.share.proto.chenmi.Chenmi.ChenmiInfoRequest buildPartial() {
        com.share.proto.chenmi.Chenmi.ChenmiInfoRequest result = new com.share.proto.chenmi.Chenmi.ChenmiInfoRequest(this);
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.share.proto.chenmi.Chenmi.ChenmiInfoRequest) {
          return mergeFrom((com.share.proto.chenmi.Chenmi.ChenmiInfoRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.share.proto.chenmi.Chenmi.ChenmiInfoRequest other) {
        if (other == com.share.proto.chenmi.Chenmi.ChenmiInfoRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.share.proto.chenmi.Chenmi.ChenmiInfoRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.share.proto.chenmi.Chenmi.ChenmiInfoRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.share.proto.chenmi.ChenmiInfoRequest)
    }

    static {
      defaultInstance = new ChenmiInfoRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.share.proto.chenmi.ChenmiInfoRequest)
  }

  public interface ChenmiInfoResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional int32 isCM = 1;
    /**
     * <code>optional int32 isCM = 1;</code>
     *
     * <pre>
     *是否沉迷，1沉迷 0不沉迷
     * </pre>
     */
    boolean hasIsCM();
    /**
     * <code>optional int32 isCM = 1;</code>
     *
     * <pre>
     *是否沉迷，1沉迷 0不沉迷
     * </pre>
     */
    int getIsCM();

    // optional int64 onlineTime = 2;
    /**
     * <code>optional int64 onlineTime = 2;</code>
     *
     * <pre>
     *在线时长，毫秒
     * </pre>
     */
    boolean hasOnlineTime();
    /**
     * <code>optional int64 onlineTime = 2;</code>
     *
     * <pre>
     *在线时长，毫秒
     * </pre>
     */
    long getOnlineTime();
  }
  /**
   * Protobuf type {@code com.share.proto.chenmi.ChenmiInfoResponse}
   *
   * <pre>
   *120010
   * </pre>
   */
  public static final class ChenmiInfoResponse extends
      com.google.protobuf.GeneratedMessage
      implements ChenmiInfoResponseOrBuilder {
    // Use ChenmiInfoResponse.newBuilder() to construct.
    private ChenmiInfoResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ChenmiInfoResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ChenmiInfoResponse defaultInstance;
    public static ChenmiInfoResponse getDefaultInstance() {
      return defaultInstance;
    }

    public ChenmiInfoResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ChenmiInfoResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              isCM_ = input.readInt32();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              onlineTime_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.share.proto.chenmi.Chenmi.internal_static_com_share_proto_chenmi_ChenmiInfoResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.share.proto.chenmi.Chenmi.internal_static_com_share_proto_chenmi_ChenmiInfoResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.share.proto.chenmi.Chenmi.ChenmiInfoResponse.class, com.share.proto.chenmi.Chenmi.ChenmiInfoResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<ChenmiInfoResponse> PARSER =
        new com.google.protobuf.AbstractParser<ChenmiInfoResponse>() {
      public ChenmiInfoResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ChenmiInfoResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ChenmiInfoResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional int32 isCM = 1;
    public static final int ISCM_FIELD_NUMBER = 1;
    private int isCM_;
    /**
     * <code>optional int32 isCM = 1;</code>
     *
     * <pre>
     *是否沉迷，1沉迷 0不沉迷
     * </pre>
     */
    public boolean hasIsCM() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional int32 isCM = 1;</code>
     *
     * <pre>
     *是否沉迷，1沉迷 0不沉迷
     * </pre>
     */
    public int getIsCM() {
      return isCM_;
    }

    // optional int64 onlineTime = 2;
    public static final int ONLINETIME_FIELD_NUMBER = 2;
    private long onlineTime_;
    /**
     * <code>optional int64 onlineTime = 2;</code>
     *
     * <pre>
     *在线时长，毫秒
     * </pre>
     */
    public boolean hasOnlineTime() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional int64 onlineTime = 2;</code>
     *
     * <pre>
     *在线时长，毫秒
     * </pre>
     */
    public long getOnlineTime() {
      return onlineTime_;
    }

    private void initFields() {
      isCM_ = 0;
      onlineTime_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, isCM_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, onlineTime_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, isCM_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, onlineTime_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.share.proto.chenmi.Chenmi.ChenmiInfoResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.share.proto.chenmi.Chenmi.ChenmiInfoResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.share.proto.chenmi.Chenmi.ChenmiInfoResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.share.proto.chenmi.Chenmi.ChenmiInfoResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.share.proto.chenmi.Chenmi.ChenmiInfoResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.share.proto.chenmi.Chenmi.ChenmiInfoResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.share.proto.chenmi.Chenmi.ChenmiInfoResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.share.proto.chenmi.Chenmi.ChenmiInfoResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.share.proto.chenmi.Chenmi.ChenmiInfoResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.share.proto.chenmi.Chenmi.ChenmiInfoResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.share.proto.chenmi.Chenmi.ChenmiInfoResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.share.proto.chenmi.ChenmiInfoResponse}
     *
     * <pre>
     *120010
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.share.proto.chenmi.Chenmi.ChenmiInfoResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.share.proto.chenmi.Chenmi.internal_static_com_share_proto_chenmi_ChenmiInfoResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.share.proto.chenmi.Chenmi.internal_static_com_share_proto_chenmi_ChenmiInfoResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.share.proto.chenmi.Chenmi.ChenmiInfoResponse.class, com.share.proto.chenmi.Chenmi.ChenmiInfoResponse.Builder.class);
      }

      // Construct using com.share.proto.chenmi.Chenmi.ChenmiInfoResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        isCM_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        onlineTime_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.share.proto.chenmi.Chenmi.internal_static_com_share_proto_chenmi_ChenmiInfoResponse_descriptor;
      }

      public com.share.proto.chenmi.Chenmi.ChenmiInfoResponse getDefaultInstanceForType() {
        return com.share.proto.chenmi.Chenmi.ChenmiInfoResponse.getDefaultInstance();
      }

      public com.share.proto.chenmi.Chenmi.ChenmiInfoResponse build() {
        com.share.proto.chenmi.Chenmi.ChenmiInfoResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.share.proto.chenmi.Chenmi.ChenmiInfoResponse buildPartial() {
        com.share.proto.chenmi.Chenmi.ChenmiInfoResponse result = new com.share.proto.chenmi.Chenmi.ChenmiInfoResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.isCM_ = isCM_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.onlineTime_ = onlineTime_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.share.proto.chenmi.Chenmi.ChenmiInfoResponse) {
          return mergeFrom((com.share.proto.chenmi.Chenmi.ChenmiInfoResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.share.proto.chenmi.Chenmi.ChenmiInfoResponse other) {
        if (other == com.share.proto.chenmi.Chenmi.ChenmiInfoResponse.getDefaultInstance()) return this;
        if (other.hasIsCM()) {
          setIsCM(other.getIsCM());
        }
        if (other.hasOnlineTime()) {
          setOnlineTime(other.getOnlineTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.share.proto.chenmi.Chenmi.ChenmiInfoResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.share.proto.chenmi.Chenmi.ChenmiInfoResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional int32 isCM = 1;
      private int isCM_ ;
      /**
       * <code>optional int32 isCM = 1;</code>
       *
       * <pre>
       *是否沉迷，1沉迷 0不沉迷
       * </pre>
       */
      public boolean hasIsCM() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional int32 isCM = 1;</code>
       *
       * <pre>
       *是否沉迷，1沉迷 0不沉迷
       * </pre>
       */
      public int getIsCM() {
        return isCM_;
      }
      /**
       * <code>optional int32 isCM = 1;</code>
       *
       * <pre>
       *是否沉迷，1沉迷 0不沉迷
       * </pre>
       */
      public Builder setIsCM(int value) {
        bitField0_ |= 0x00000001;
        isCM_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 isCM = 1;</code>
       *
       * <pre>
       *是否沉迷，1沉迷 0不沉迷
       * </pre>
       */
      public Builder clearIsCM() {
        bitField0_ = (bitField0_ & ~0x00000001);
        isCM_ = 0;
        onChanged();
        return this;
      }

      // optional int64 onlineTime = 2;
      private long onlineTime_ ;
      /**
       * <code>optional int64 onlineTime = 2;</code>
       *
       * <pre>
       *在线时长，毫秒
       * </pre>
       */
      public boolean hasOnlineTime() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional int64 onlineTime = 2;</code>
       *
       * <pre>
       *在线时长，毫秒
       * </pre>
       */
      public long getOnlineTime() {
        return onlineTime_;
      }
      /**
       * <code>optional int64 onlineTime = 2;</code>
       *
       * <pre>
       *在线时长，毫秒
       * </pre>
       */
      public Builder setOnlineTime(long value) {
        bitField0_ |= 0x00000002;
        onlineTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 onlineTime = 2;</code>
       *
       * <pre>
       *在线时长，毫秒
       * </pre>
       */
      public Builder clearOnlineTime() {
        bitField0_ = (bitField0_ & ~0x00000002);
        onlineTime_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.share.proto.chenmi.ChenmiInfoResponse)
    }

    static {
      defaultInstance = new ChenmiInfoResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.share.proto.chenmi.ChenmiInfoResponse)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_share_proto_chenmi_ChenmiInfoRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_share_proto_chenmi_ChenmiInfoRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_share_proto_chenmi_ChenmiInfoResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_share_proto_chenmi_ChenmiInfoResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023protos/chenmi.proto\022\026com.share.proto.c" +
      "henmi\"\023\n\021ChenmiInfoRequest\"6\n\022ChenmiInfo" +
      "Response\022\014\n\004isCM\030\001 \001(\005\022\022\n\nonlineTime\030\002 \001" +
      "(\003"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_share_proto_chenmi_ChenmiInfoRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_share_proto_chenmi_ChenmiInfoRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_share_proto_chenmi_ChenmiInfoRequest_descriptor,
              new java.lang.String[] { });
          internal_static_com_share_proto_chenmi_ChenmiInfoResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_share_proto_chenmi_ChenmiInfoResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_share_proto_chenmi_ChenmiInfoResponse_descriptor,
              new java.lang.String[] { "IsCM", "OnlineTime", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
